// <auto-generated />
namespace BuddySystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedICollectionVolunteer_To_Buddy_Applied_modelBuilder_function_to_IdentityModelsApplicationdDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedICollectionVolunteer_To_Buddy_Applied_modelBuilder_function_to_IdentityModelsApplicationdDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201911220150271_AddedICollectionVolunteer_To_Buddy_Applied_modelBuilder_function_to_IdentityModelsApplicationdDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
